# Generated by Django 4.2.8 on 2025-09-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_quizquestion_alter_customuser_role_quizresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='category',
            field=models.CharField(choices=[('lawbasics', 'Law Basics Quiz'), ('beginner', '📘 Beginner Quizzes'), ('subjectwise', '⚖️ Subject-wise Quizzes'), ('examprep', '🎓 Exam Prep Quizzes'), ('challenge', '🧠 Challenge Quizzes')], default='lawbasics', max_length=20),
        ),
    ]
