# Generated by Django 4.2.8 on 2025-09-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ipc', 'Indian Penal Code'), ('crpc', 'Code of Criminal Procedure'), ('rights', 'Legal Rights'), ('process', 'Legal Processes')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
