# Generated by Django 4.2.8 on 2025-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_legalarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalLearnResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(choices=[('constitution', 'Indian Constitution'), ('evidence', 'Evidence Act'), ('contract', 'Contract Law'), ('tort', 'Tort Law'), ('casebrief', 'Case Briefing'), ('research', 'Legal Research')], max_length=30)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
