# Generated by Django 4.2.8 on 2025-09-22 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_legallearnresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('rent_agreement', 'Rent Agreement'), ('affidavit', 'Affidavit'), ('nda', 'Non-Disclosure Agreement')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('short_description', models.TextField()),
                ('fields_json', models.TextField(help_text='JSON describing form fields and labels')),
                ('template_text', models.TextField(help_text='Use {{field_name}} for placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalGeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_data', models.JSONField(blank=True, null=True)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='generated_docs/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('doc_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.legaldoctemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
