# Generated by Django 4.2.8 on 2025-10-07 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_legalchatmessage_delete_legalbotchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_filed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
